name: .NET Core CI with xUnit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: main restore E-Vita.sln

      - name: Build Project
        run: main build E-Vita.sln --configuration Release --no-restore

      - name: Run Tests
        run: main test E-Vita.csproj --configuration Release --no-build --verbosity normal
